version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout:
          path: systemseed_assessment

      - run:
          name: Install SQLite driver
          command: sudo apt-get update && sudo apt-get install -y php8.1-sqlite3

      - run:
          name: Create and install Drupal project
          command: composer create-project drupal/recommended-project:^9 drupal

      - run:
          name: Install project dependencies
          working_directory: drupal
          command: |
            composer config repositories.systemseed/systemseed_assessment path ../systemseed_assessment && \
            composer config minimum-stability dev && \
            composer require systemseed/systemseed_assessment:*@dev && \
            composer require --dev drupal/core-dev:^9 && \
            composer require --dev dealerdirect/phpcodesniffer-composer-installer

      - run:
          name: Run PHP code sniffer to check Drupal coding standards
          working_directory: drupal
          command: |
            vendor/bin/phpcs --standard=Drupal --ignore=node_modules,vendor,dist,js web/modules/contrib/systemseed_assessment/

      - run:
          name: Run test
          working_directory: drupal
          command: php -S localhost:8888 -t web/ & sleep 1 && php web/core/scripts/run-tests.sh --sqlite /tmp/drupal/runner.sqlite --dburl sqlite://localhost//tmp/drupal/test.sqlite --url http://localhost:8888 --module systemseed_assessment --verbose --suppress-deprecations
